name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      # If you don't have a requirements.txt, this line won't fail the job
      - run: python -m pip install -r requirements.txt || true
      - run: bash scripts/smoke.sh