name: Build and Push
on:
  push:
    branches: [staging, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: |
          SHA="${GITHUB_SHA::7}"
          REF="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-ci}}"
          REF="${REF//\//-}"
          REF="$(echo "$REF" | sed 's/[^A-Za-z0-9_.-]/-/g')"
          REF="${REF:-ci}"
          echo "IMAGE_TAG=build-${REF}-${SHA}" >> "$GITHUB_ENV"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
