name: ci
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" || pip install -r requirements.txt
      - name: Install
        run: pip install -e .[dev]
      - name: Lint
        run: ruff check . && ruff format --check .
      - name: Tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1
        run: pytest -q -c pytest.ini
      - name: Smoke
        run: |
          bash scripts/smoke.sh
