name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e .[dev]
      - run: ruff check .
      - run: ruff format --check .
      - run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -q -c pytest.ini
