name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: vectorbid_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev gcc

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      run: |
        ruff check . --select=E9,F63,F7,F82
        ruff check . --exit-zero
        ruff format --check .

    - name: Run security scan
      run: |
        bandit -r . -ll --exclude tests/,validate_openapi.py,test_api.py

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vectorbid_test
        SECRET_KEY: test-secret-key-for-github-actions
        ADMIN_BEARER_TOKEN: test-admin-token-for-github-actions
        FLASK_ENV: testing
      run: |
        pytest tests/ -v