name: Smoke
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHONPATH: "."
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PORT: "8080"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]" || pip install -r requirements.txt
      - name: Run smoke
        run: bash scripts/smoke.sh
